### ISSUE TITLE
Feature of send() in vyper 

### ISSUE THREAD

**Issue by osuketh** [LayerXcom/plasma-mvp-vyper#62]
send() in vyper is same as call.value() in solidity? It means, if it fails, it returns `revert` , not `false` . And fallback function can be executed over 2,300 gas.

**Comment by nrryuya** [comment]
- `send` will revert
https://github.com/ethereum/vyper/pull/314#issuecomment-321359701

- Defense for reentrancy with 2300 gas is not supported (from gitter)

**Comment by osuketh** [comment]
https://github.com/ethereum/vyper/issues/899
`send()` function used over 2,300gas will be failed. But, `raw_call()` can send more gas.
