### ISSUE TITLE
vyper testどうやる？

### ISSUE THREAD

**Issue by osuketh** [LayerXcom/plasma-mvp-vyper#7]
vyperのtestのベストプラクティスは？

**Comment by nrryuya** [comment]
https://github.com/maurelian/erc721-vyper
普通にtruffle使ってテスト書いてる

**Comment by nrryuya** [comment]
ゆくゆくはtruffleでビルド通してからプルリクマージする流れにしたいですね
下記ディレクトリ以下が新しくなっていく感じ
https://github.com/maurelian/erc721-vyper/tree/master/build/contracts

**Comment by nrryuya** [comment]
Migrationはsolidity？よくわからず
https://github.com/maurelian/erc721-vyper/blob/master/contracts/Migrations.sol

**Comment by nrryuya** [comment]
populous
https://qiita.com/naoki_maeda/items/25fd28777d04e144aea4

**Comment by osuketh** [comment]
Compile and deploy Vyper smart contracts to Truffle Develop or a private Geth Node using Web3.py, then mine the transaction and view the transaction receipt before call its functions
https://github.com/ltfschoen/vyper-test

**Comment by nrryuya** [comment]
#21 
use OmiseGo's style test(python)
